theme: jekyll-theme-minimal
title: Welcome to leonhx's homepage
description: Still under construction. Feel free to look around.
# logo: [Location of the logo]
# google_analytics: [Your Google Analytics tracking ID]
